const searches = [
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 6,000 و الـ 7,999",
    price: "أقل من 100 ألف",
    email: "knakri01@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "mouhammed.almasri.cm7@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "متجر",
    business_offer: "إجار",
    area: "أقل من 20",
    price: "أقل من 100 ألف",
    email: "ahmad50164@gmail.com",
    region: "درعا-داعل",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 180 و الـ 199",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "adnankanakri3@gmail.com",
    region: "درعا-داعل",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 180 و الـ 199",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "adnankanakri3@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "mouhammed.almasri.cm7@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "mouhammed.almasri.cm7@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "مكتب",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 500 ألف وأصغر من 600 ألف",
    email: "kalelehamd@gmail.com",
    region: "ريف دمشق-يبرود",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "alan.ite101@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أقل من 100 ألف",
    email: "mouhammed.almasri.cm7@gmail.com",
    region: "درعا-داعل",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 120 و الـ 139",
    price: "أقل من 100 ألف",
    email: "ahmad50164@yahoo.com",
    region: "درعا-داعل",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 500 و الـ 599",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "alan.ite101@gmail.com",
    region: "دمشق-كفرسوسة",
  },
  {
    offer_type: "مكتب",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "alan.ite101@gmail.com",
    region: "دمشق-دمر",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 180 و الـ 199",
    price: "أكبر من 7 مليون وأصغر من 10 مليون",
    email: "alan.ite101@gmail.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 200 و الـ 239",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "kalelehamd@gmail.com",
    region: "دمشق-برزة",
  },
  {
    offer_type: "مكتب",
    business_offer: "شراء",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من مليون وأصغر من 1.5 مليون",
    email: "kalelehamd@gmail.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "متجر",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "kalelehamd@gmail.com",
    region: "دمشق-دمر",
  },
  {
    offer_type: "متجر",
    business_offer: "إجار",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "alan.ite101@gmail.com",
    region: "اللاذقية-مركز اللاذقية",
  },
  {
    offer_type: "قبو",
    business_offer: "شراء",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 7 مليون وأصغر من 10 مليون",
    email: "kalelehamd@gmail.com",
    region: "ريف دمشق-عين الفيجة",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 7 مليون وأصغر من 10 مليون",
    email: "mamounaljamous98@gmail.com",
    region: "درعا-مركز درعا",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 800 و الـ 999",
    price: "أكبر من 260 مليون وأصغر من 300 مليون",
    email: "mamounaljamous98@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "مكتب",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "meme.222887m@gmail.com",
    region: "السويداء-مركز السويداء",
  },
  {
    offer_type: "أرض",
    business_offer: "شراء",
    area: "بين الـ 6,000 و الـ 7,999",
    price: "أكبر من 50 مليون وأصغر من 60 مليون",
    email: "mamounaljamous98@gmail.com",
    region: "درعا-داعل",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 180 و الـ 199",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "mohammed8araby@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "waelorabi267@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "shamhasn133@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "reemhusein995@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "emanshmma98@gmail.com",
    region: "دمشق-دمشق القديمة",
  },
  {
    offer_type: "مزرعة",
    business_offer: "شراء",
    area: "بين الـ 360 و الـ 399",
    price: "أكبر من 140 مليون وأصغر من 180 مليون",
    email: "emanshmma98@gmail.com",
    region: "ريف دمشق-سرغايا",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 800 ألف وأصغر من مليون",
    email: "srmadshama@gmail.com",
    region: "حلب-مركز حلب",
  },
  {
    offer_type: "شالية",
    business_offer: "شراء",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 300 ألف وأصغر من 400 ألف",
    email: "mohmdgzghshzvhsh@gmal.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 5 مليون وأصغر من 7 مليون",
    email: "shamo-b950@hotmil.com",
    region: "دمشق-الصالحية",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 80 مليون وأصغر من 100 مليون",
    email: "sana-tean@gmail.com",
    region: "دمشق-كفرسوسة",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 12,000 و الـ 15,999",
    price: "أكبر من مليون وأصغر من 1.5 مليون",
    email: "yomna@gamil.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "مطعم",
    business_offer: "شراء",
    area: "بين الـ 200 و الـ 239",
    price: "أكبر من 7 مليون وأصغر من 10 مليون",
    email: "wallaa90sh@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 500 و الـ 599",
    price: "أكبر من 40 مليون وأصغر من 50 مليون",
    email: "rimaalrifai19@gmail.com",
    region: "ريف دمشق-ضاحية قدسيا",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "أقل من 20",
    price: "أقل من 100 ألف",
    email: "mohannad@gmail.com",
    region: "دمشق-الشاغور",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 7 مليون وأصغر من 10 مليون",
    email: "mohannad@gmail.com",
    region: "دمشق-الشاغور",
  },
  {
    offer_type: "شالية",
    business_offer: "إجار",
    area: "أقل من 20",
    price: "أقل من 100 ألف",
    email: "mohannad@gmail.com",
    region: "اللاذقية-هنادي",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أقل من 100 ألف",
    email: "mmnnman71@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 10 مليون وأصغر من 15 مليون",
    email: "mohannad@gmail.com",
    region: "دمشق-الشاغور",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 800 و الـ 999",
    price: "أقل من 100 ألف",
    email: "mmnnman71@gmail.com",
    region: "ريف دمشق-الكسوة",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 300 ألف وأصغر من 400 ألف",
    email: "rawda.rose.4@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 5 مليون وأصغر من 7 مليون",
    email: "sohelanasry21@gmail.com",
    region: "ريف دمشق-كفر بطنا",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 280 و الـ 319",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "12345@g.com",
    region: "ريف دمشق-دوما",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "12345@g.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "مكتب",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 2 مليون وأصغر من 3 مليون",
    email: "12345@g.com",
    region: "دمشق-الصالحية",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من مليون وأصغر من 1.5 مليون",
    email: "12345@g.com",
    region: "حلب-رسم حرمل الامام",
  },
  {
    offer_type: "مطعم",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 400 ألف وأصغر من 500 ألف",
    email: "12345@g.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "samirahassan98@hotmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 180 مليون وأصغر من 220 مليون",
    email: "sameh.juha@hotmail.com",
    region: "ريف دمشق-ضاحية قدسيا",
  },
  {
    offer_type: "شالية",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أقل من 100 ألف",
    email: "sameh.juha@hotmail.com",
    region: "اللاذقية-مركز اللاذقية",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 80 مليون وأصغر من 100 مليون",
    email: "mhmd204sy@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "mafiaman000@hotmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "mafiaman000@hotmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 600 و الـ 799",
    price: "أكبر من 800 مليون وأصغر من 900 مليون",
    email: "noortarboosh86@gmail.com",
    region: "حلب-سيف الدولة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 320 و الـ 359",
    price: "أكبر من 450 مليون وأصغر من 500 مليون",
    email: "noortarboosh86@gmail.com",
    region: "دمشق-دمشق القديمة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "fayrouzalkhalil@gmail.com",
    region: "دمشق-اليرموك",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 50 مليون وأصغر من 60 مليون",
    email: "Denaaalheany1998@hotmail.com",
    region: "ريف دمشق-الكسوة",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 20,000 و الـ 100,000",
    price: "أكبر من مليار وأصغر من 10 مليار",
    email: "mmmmmmmmm@mmm.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 500 ألف وأصغر من 600 ألف",
    email: "Ayat24247@gmail.com",
    region: "ريف دمشق-حرستا",
  },
  {
    offer_type: "شالية",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "emanshmma98@gmail.com",
    region: "اللاذقية-كسب",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 200 و الـ 239",
    price: "أقل من 100 ألف",
    email: "emanshmma98@gmail.com",
    region: "ريف دمشق-مضايا",
  },
  {
    offer_type: "شالية",
    business_offer: "شراء",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "raghadshibli@gmail.com",
    region: "اللاذقية-جبلة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 80 مليون وأصغر من 100 مليون",
    email: "fatimaalzh199895@gmail.com",
    region: "دمشق-الصالحية",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 80 و الـ 99",
    price: "أقل من 100 ألف",
    email: "eyad.20.3.87@gmail.com",
    region: "حلب-سيف الدولة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "technomacx@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 260 مليون وأصغر من 300 مليون",
    email: "obaa@gmail.com",
    region: "دمشق-المهاجرين",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 350 مليون وأصغر من 400 مليون",
    email: "obaa@gmail.com",
    region: "دمشق-المهاجرين",
  },
  {
    offer_type: "مكتب",
    business_offer: "شراء",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 80 مليون وأصغر من 100 مليون",
    email: "renadalbunni98@hotmail.com",
    region: "دمشق-القصاع",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 20 مليون وأصغر من 30 مليون",
    email: "xxxxx@hotmail.com",
    region: "ريف دمشق-التل",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "aydihadia@gmail.com",
    region: "ريف دمشق-قدسيا",
  },
  {
    offer_type: "شالية",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "rrrrrr@hotmail.com",
    region: "اللاذقية-كسب",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "rrr@hotmail.com",
    region: "ريف دمشق-صحنايا",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أقل من 100 ألف",
    email: "Etabf59@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 200 و الـ 239",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "malcharif@darsoft.net",
    region: "ريف دمشق-الزبداني",
  },
  {
    offer_type: "مكتب",
    business_offer: "إجار",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 300 ألف وأصغر من 400 ألف",
    email: "malcharif@darsoft.net",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 160 و الـ 179",
    price: "أكبر من 10 مليون وأصغر من 15 مليون",
    email: "doaa1@gmail.com",
    region: "دمشق-المهاجرين",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 120 و الـ 139",
    price: "أكبر من 700 مليون وأصغر من 800 مليون",
    email: "alishipli1998@hotmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "r.zyadeh@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أقل من 100 ألف",
    email: "ayooshka114@gmail.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 3,000 و الـ 3,999",
    price: "أكبر من مليار وأصغر من 10 مليار",
    email: "shwshw.gh97@gmail.com",
    region: "دمشق-كفرسوسة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "waad.ghussn10@gmail.com",
    region: "ريف دمشق-النبك",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "ayoosh2016@gmail.com",
    region: "دمشق-كفرسوسة",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "test@gmail.con",
    region: "دمشق-المزة",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 120 و الـ 139",
    price: "أقل من 100 ألف",
    email: "mosup1995@gmail.com",
    region: "ريف دمشق-الزبداني",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "almar39615@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 500 ألف وأصغر من 600 ألف",
    email: "ramamaks@gmail.com",
    region: "دمشق-كفرسوسة",
  },
  {
    offer_type: "شالية",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "almar39615@gmail.com",
    region: "اللاذقية-جبلة",
  },
  {
    offer_type: "فيلا",
    business_offer: "شراء",
    area: "بين الـ 20,000 و الـ 100,000",
    price: "أكبر من مليار وأصغر من 10 مليار",
    email: "mostafajomaa@example.com",
    region: "دمشق-ركن الدين",
  },
  {
    offer_type: "أرض",
    business_offer: "شراء",
    area: "بين الـ 8,000 و الـ 9,999",
    price: "أكبر من 600 مليون وأصغر من 700 مليون",
    email: "mostafajomaa@example.com",
    region: "ريف دمشق-دوما",
  },
  {
    offer_type: "مستودع",
    business_offer: "إجار",
    area: "بين الـ 180 و الـ 199",
    price: "أكبر من 800 ألف وأصغر من مليون",
    email: "mostafajomaa@example.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شالية",
    business_offer: "شراء",
    area: "بين الـ 320 و الـ 359",
    price: "أكبر من 260 مليون وأصغر من 300 مليون",
    email: "mostafajomaa@example.com",
    region: "اللاذقية-جبلة",
  },
  {
    offer_type: "قبو",
    business_offer: "إجار",
    area: "بين الـ 1,000 و الـ 1,199",
    price: "أكبر من 600 ألف وأصغر من 800 ألف",
    email: "mostafajomaa@example.com",
    region: "دمشق-القنوات",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 15 مليون وأصغر من 20 مليون",
    email: "harryheba@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 400 مليون وأصغر من 450 مليون",
    email: "moazberkdar9@gmail.com",
    region: "دمشق-برزة",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 200 ألف وأصغر من 300 ألف",
    email: "mhmoodalkma22@gmail.com",
    region: "دمشق-المزة",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 200 و الـ 239",
    price: "أكبر من 15 مليون وأصغر من 20 مليون",
    email: "mhmoudibrahim33@gmail.com",
    region: "ريف دمشق-كفر بطنا",
  },
  {
    offer_type: "فيلا",
    business_offer: "إجار",
    area: "بين الـ 1,200 و الـ 1,599",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "mhmoodasmaeel35@gmail.com",
    region: "ريف دمشق-الزبداني",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 140 و الـ 159",
    price: "أكبر من 600 مليون وأصغر من 700 مليون",
    email: "kareem.draawe3@gmail.com",
    region: "دمشق-القصاع",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 20 و الـ 39",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "alan.ite101@gmail.com",
    region: "دمشق-المهاجرين",
  },
  {
    offer_type: "بيت",
    business_offer: "شراء",
    area: "بين الـ 100 و الـ 119",
    price: "أكبر من 100 مليون وأصغر من 140 مليون",
    email: "mmnnman71@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "بيت",
    business_offer: "إجار",
    area: "بين الـ 60 و الـ 79",
    price: "أكبر من 150 ألف وأصغر من 200 ألف",
    email: "roidaawad@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "شقة",
    business_offer: "شراء",
    area: "بين الـ 80 و الـ 99",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "safaakiwan@gmail.com",
    region: "ريف دمشق-جرمانا",
  },
  {
    offer_type: "شقة",
    business_offer: "إجار",
    area: "بين الـ 40 و الـ 59",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "sh099711@gmail.com",
    region: "دمشق-الميدان",
  },
  {
    offer_type: "مزرعة",
    business_offer: "إجار",
    area: "بين الـ 200 و الـ 239",
    price: "أكبر من 100 ألف وأصغر من 150 ألف",
    email: "anessaalkhalil@gamil.com",
    region: "ريف دمشق-جرمانا",
  },
];

module.exports = searches;
