const search_data = [
  {
    email: "knakri01@gmail.com",
    firstName: "Hani",
    lastName: "Kanakri",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "daeil",
    birthday: "1998-11-02",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 6,000 و الـ 7,999",
        price: "أقل من 100 ألف",
        email: "knakri01@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "mouhammed.almasri.cm7@gmail.com",
    firstName: "Mohammed",
    lastName: "Masri",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "daeil",
    birthday: "1998-02-16",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "mouhammed.almasri.cm7@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "mouhammed.almasri.cm7@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "mouhammed.almasri.cm7@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أقل من 100 ألف",
        email: "mouhammed.almasri.cm7@gmail.com",
        region: "درعا-داعل",
      },
    ],
  },
  {
    email: "ahmad50164@gmail.com",
    firstName: "Ahmad",
    lastName: "A",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaydan",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "متجر",
        business_offer: "إجار",
        area: "أقل من 20",
        price: "أقل من 100 ألف",
        email: "ahmad50164@gmail.com",
        region: "درعا-داعل",
      },
    ],
  },
  {
    email: "adnankanakri3@gmail.com",
    firstName: "Adnan",
    lastName: "Kanakri",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "daeil",
    birthday: "1997-08-27",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 180 و الـ 199",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "adnankanakri3@gmail.com",
        region: "درعا-داعل",
      },
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 180 و الـ 199",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "adnankanakri3@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "kalelehamd@gmail.com",
    firstName: "kalel",
    lastName: "Ahamd",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "barza",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مكتب",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 500 ألف وأصغر من 600 ألف",
        email: "kalelehamd@gmail.com",
        region: "ريف دمشق-يبرود",
      },
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 200 و الـ 239",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "kalelehamd@gmail.com",
        region: "دمشق-برزة",
      },
      {
        offer_type: "مكتب",
        business_offer: "شراء",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من مليون وأصغر من 1.5 مليون",
        email: "kalelehamd@gmail.com",
        region: "دمشق-ركن الدين",
      },
      {
        offer_type: "متجر",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "kalelehamd@gmail.com",
        region: "دمشق-دمر",
      },
      {
        offer_type: "قبو",
        business_offer: "شراء",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 7 مليون وأصغر من 10 مليون",
        email: "kalelehamd@gmail.com",
        region: "ريف دمشق-عين الفيجة",
      },
    ],
  },
  {
    email: "alan.ite101@gmail.com",
    firstName: "Alan",
    lastName: "I",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "alan.ite101@gmail.com",
        region: "دمشق-المزة",
      },
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 500 و الـ 599",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "alan.ite101@gmail.com",
        region: "دمشق-كفرسوسة",
      },
      {
        offer_type: "مكتب",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "alan.ite101@gmail.com",
        region: "دمشق-دمر",
      },
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 180 و الـ 199",
        price: "أكبر من 7 مليون وأصغر من 10 مليون",
        email: "alan.ite101@gmail.com",
        region: "دمشق-ركن الدين",
      },
      {
        offer_type: "متجر",
        business_offer: "إجار",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "alan.ite101@gmail.com",
        region: "اللاذقية-مركز اللاذقية",
      },
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "alan.ite101@gmail.com",
        region: "دمشق-المهاجرين",
      },
    ],
  },
  {
    email: "ahmad50164@yahoo.com",
    firstName: "Ahmad",
    lastName: "A",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "daeil",
    birthday: "1993-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 120 و الـ 139",
        price: "أقل من 100 ألف",
        email: "ahmad50164@yahoo.com",
        region: "درعا-داعل",
      },
    ],
  },
  {
    email: "mamounaljamous98@gmail.com",
    firstName: "Mamoun",
    lastName: "Jamous",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "daeil",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 7 مليون وأصغر من 10 مليون",
        email: "mamounaljamous98@gmail.com",
        region: "درعا-مركز درعا",
      },
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 800 و الـ 999",
        price: "أكبر من 260 مليون وأصغر من 300 مليون",
        email: "mamounaljamous98@gmail.com",
        region: "دمشق-المزة",
      },
      {
        offer_type: "أرض",
        business_offer: "شراء",
        area: "بين الـ 6,000 و الـ 7,999",
        price: "أكبر من 50 مليون وأصغر من 60 مليون",
        email: "mamounaljamous98@gmail.com",
        region: "درعا-داعل",
      },
    ],
  },
  {
    email: "meme.222887m@gmail.com",
    firstName: "Meme",
    lastName: "m",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "markaz-alsuwayda",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مكتب",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "meme.222887m@gmail.com",
        region: "السويداء-مركز السويداء",
      },
    ],
  },
  {
    email: "mohammed8araby@gmail.com",
    firstName: "Mohammed",
    lastName: "Araby",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 180 و الـ 199",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "mohammed8araby@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "waelorabi267@gmail.com",
    firstName: "Wael",
    lastName: "Prabi",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "waelorabi267@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "shamhasn133@gmail.com",
    firstName: "Sham",
    lastName: "Hasan",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "shamhasn133@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "reemhusein995@gmail.com",
    firstName: "Reem",
    lastName: "Hasan",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1996-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "reemhusein995@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "emanshmma98@gmail.com",
    firstName: "Eman",
    lastName: "Shamma",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "emanshmma98@gmail.com",
        region: "دمشق-دمشق القديمة",
      },
      {
        offer_type: "مزرعة",
        business_offer: "شراء",
        area: "بين الـ 360 و الـ 399",
        price: "أكبر من 140 مليون وأصغر من 180 مليون",
        email: "emanshmma98@gmail.com",
        region: "ريف دمشق-سرغايا",
      },
      {
        offer_type: "شالية",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "emanshmma98@gmail.com",
        region: "اللاذقية-كسب",
      },
      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 200 و الـ 239",
        price: "أقل من 100 ألف",
        email: "emanshmma98@gmail.com",
        region: "ريف دمشق-مضايا",
      },
    ],
  },
  {
    email: "srmadshama@gmail.com",
    firstName: "Srmad",
    lastName: "Shamma",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "markaz-halab",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 800 ألف وأصغر من مليون",
        email: "srmadshama@gmail.com",
        region: "حلب-مركز حلب",
      },
    ],
  },
  {
    email: "mohmdgzghshzvhsh@gmal.com",
    firstName: "Mohmd",
    lastName: "gz",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "rukn-aldiyn",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شالية",
        business_offer: "شراء",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 300 ألف وأصغر من 400 ألف",
        email: "mohmdgzghshzvhsh@gmal.com",
        region: "دمشق-ركن الدين",
      },
    ],
  },
  {
    email: "shamo-b950@hotmil.com",
    firstName: "Shamo",
    lastName: "b",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alsaalihia",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 5 مليون وأصغر من 7 مليون",
        email: "shamo-b950@hotmil.com",
        region: "دمشق-الصالحية",
      },
    ],
  },
  {
    email: "sana-tean@gmail.com",
    firstName: "Sana",
    lastName: "Tean",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "kafrisusa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 80 مليون وأصغر من 100 مليون",
        email: "sana-tean@gmail.com",
        region: "دمشق-كفرسوسة",
      },
    ],
  },
  {
    email: "yomna@gamil.com",
    firstName: "Yomna",
    lastName: "Y",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "rukn-aldiyn",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 12,000 و الـ 15,999",
        price: "أكبر من مليون وأصغر من 1.5 مليون",
        email: "yomna@gamil.com",
        region: "دمشق-ركن الدين",
      },
    ],
  },
  {
    email: "wallaa90sh@gmail.com",
    firstName: "Walla",
    lastName: "Sh",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مطعم",
        business_offer: "شراء",
        area: "بين الـ 200 و الـ 239",
        price: "أكبر من 7 مليون وأصغر من 10 مليون",
        email: "wallaa90sh@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "rimaalrifai19@gmail.com",
    firstName: "Rima",
    lastName: "Rifai",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "dahiat-qudsiaa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 500 و الـ 599",
        price: "أكبر من 40 مليون وأصغر من 50 مليون",
        email: "rimaalrifai19@gmail.com",
        region: "ريف دمشق-ضاحية قدسيا",
      },
    ],
  },
  {
    email: "mohannad@gmail.com",
    firstName: "Mohannad",
    lastName: "M",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "alshaaghwr",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "أقل من 20",
        price: "أقل من 100 ألف",
        email: "mohannad@gmail.com",
        region: "دمشق-الشاغور",
      },
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 7 مليون وأصغر من 10 مليون",
        email: "mohannad@gmail.com",
        region: "دمشق-الشاغور",
      },
      {
        offer_type: "شالية",
        business_offer: "إجار",
        area: "أقل من 20",
        price: "أقل من 100 ألف",
        email: "mohannad@gmail.com",
        region: "اللاذقية-هنادي",
      },
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 10 مليون وأصغر من 15 مليون",
        email: "mohannad@gmail.com",
        region: "دمشق-الشاغور",
      },
    ],
  },
  {
    email: "mmnnman71@gmail.com",
    firstName: "M",
    lastName: "N",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "alshaaghwr",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أقل من 100 ألف",
        email: "mmnnman71@gmail.com",
        region: "دمشق-الميدان",
      },

      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 800 و الـ 999",
        price: "أقل من 100 ألف",
        email: "mmnnman71@gmail.com",
        region: "ريف دمشق-الكسوة",
      },
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "mmnnman71@gmail.com",
        region: "دمشق-الميدان",
      },
    ],
  },
  {
    email: "rawda.rose.4@gmail.com",
    firstName: "Rawda",
    lastName: "Rose",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaydan",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 300 ألف وأصغر من 400 ألف",
        email: "rawda.rose.4@gmail.com",
        region: "دمشق-الميدان",
      },
    ],
  },
  {
    email: "sohelanasry21@gmail.com",
    firstName: "Sohel",
    lastName: "Ansary",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "kafar-batnana",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 5 مليون وأصغر من 7 مليون",
        email: "sohelanasry21@gmail.com",
        region: "ريف دمشق-كفر بطنا",
      },
    ],
  },
  {
    email: "12345@g.com",
    firstName: "123",
    lastName: "45",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 280 و الـ 319",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "12345@g.com",
        region: "ريف دمشق-دوما",
      },
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "12345@g.com",
        region: "دمشق-المزة",
      },
      {
        offer_type: "مكتب",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 2 مليون وأصغر من 3 مليون",
        email: "12345@g.com",
        region: "دمشق-الصالحية",
      },
      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من مليون وأصغر من 1.5 مليون",
        email: "12345@g.com",
        region: "حلب-رسم حرمل الامام",
      },
      {
        offer_type: "مطعم",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 400 ألف وأصغر من 500 ألف",
        email: "12345@g.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "samirahassan98@hotmail.com",
    firstName: "Samira",
    lastName: "Hassan",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "samirahassan98@hotmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "sameh.juha@hotmail.com",
    firstName: "Sameh",
    lastName: "Juha",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "markaz-allaadhiqia",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 180 مليون وأصغر من 220 مليون",
        email: "sameh.juha@hotmail.com",
        region: "ريف دمشق-ضاحية قدسيا",
      },
      {
        offer_type: "شالية",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أقل من 100 ألف",
        email: "sameh.juha@hotmail.com",
        region: "اللاذقية-مركز اللاذقية",
      },
    ],
  },
  {
    email: "mhmd204sy@gmail.com",
    firstName: "Mhmd",
    lastName: "sy",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 80 مليون وأصغر من 100 مليون",
        email: "mhmd204sy@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "mafiaman000@hotmail.com",
    firstName: "Iman",
    lastName: "M",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaydan",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "mafiaman000@hotmail.com",
        region: "دمشق-الميدان",
      },
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "mafiaman000@hotmail.com",
        region: "دمشق-الميدان",
      },
    ],
  },
  {
    email: "noortarboosh86@gmail.com",
    firstName: "Noor",
    lastName: "Tarboosh",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "sayf-alduwalih",
    birthday: "1986-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 600 و الـ 799",
        price: "أكبر من 800 مليون وأصغر من 900 مليون",
        email: "noortarboosh86@gmail.com",
        region: "حلب-سيف الدولة",
      },
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 320 و الـ 359",
        price: "أكبر من 450 مليون وأصغر من 500 مليون",
        email: "noortarboosh86@gmail.com",
        region: "دمشق-دمشق القديمة",
      },
    ],
  },
  {
    email: "fayrouzalkhalil@gmail.com",
    firstName: "Fayrouz",
    lastName: "Khalil",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alyarmuk",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "fayrouzalkhalil@gmail.com",
        region: "دمشق-اليرموك",
      },
    ],
  },
  {
    email: "denaaalheany1998@hotmail.com",
    firstName: "Dena",
    lastName: "Heany",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alkaswa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 50 مليون وأصغر من 60 مليون",
        email: "Denaaalheany1998@hotmail.com",
        region: "ريف دمشق-الكسوة",
      },
    ],
  },
  {
    email: "mmmmmmmmm@mmm.com",
    firstName: "M",
    lastName: "M",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 20,000 و الـ 100,000",
        price: "أكبر من مليار وأصغر من 10 مليار",
        email: "mmmmmmmmm@mmm.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "ayat24247@gmail.com",
    firstName: "Ayat",
    lastName: "sy",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "harasta",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 500 ألف وأصغر من 600 ألف",
        email: "Ayat24247@gmail.com",
        region: "ريف دمشق-حرستا",
      },
    ],
  },
  {
    email: "raghadshibli@gmail.com",
    firstName: "Raghad",
    lastName: "Shibli",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شالية",
        business_offer: "شراء",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "raghadshibli@gmail.com",
        region: "اللاذقية-جبلة",
      },
    ],
  },
  {
    email: "fatimaalzh199895@gmail.com",
    firstName: "Fatima",
    lastName: "Alzh",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alsaalihia",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 80 مليون وأصغر من 100 مليون",
        email: "fatimaalzh199895@gmail.com",
        region: "دمشق-الصالحية",
      },
    ],
  },
  {
    email: "eyad.20.3.87@gmail.com",
    firstName: "Eyad",
    lastName: "E",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "sayf-alduwalih",
    birthday: "1987-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 80 و الـ 99",
        price: "أقل من 100 ألف",
        email: "eyad.20.3.87@gmail.com",
        region: "حلب-سيف الدولة",
      },
    ],
  },
  {
    email: "obaa@gmail.com",
    firstName: "Obada",
    lastName: "Maleh",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almuhajirin",
    birthday: "2001-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 260 مليون وأصغر من 300 مليون",
        email: "obaa@gmail.com",
        region: "دمشق-المهاجرين",
      },
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 350 مليون وأصغر من 400 مليون",
        email: "obaa@gmail.com",
        region: "دمشق-المهاجرين",
      },
    ],
  },
  {
    email: "renadalbunni98@hotmail.com",
    firstName: "Renad",
    lastName: "Bunni",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alqisae",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مكتب",
        business_offer: "شراء",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 80 مليون وأصغر من 100 مليون",
        email: "renadalbunni98@hotmail.com",
        region: "دمشق-القصاع",
      },
    ],
  },
  {
    email: "xxxxx@hotmail.com",
    firstName: "xxxx",
    lastName: "xxxx",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "altall",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 20 مليون وأصغر من 30 مليون",
        email: "xxxxx@hotmail.com",
        region: "ريف دمشق-التل",
      },
    ],
  },
  {
    email: "aydihadia@gmail.com",
    firstName: "Aydih",
    lastName: "Adia",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "qudsiaa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "aydihadia@gmail.com",
        region: "ريف دمشق-قدسيا",
      },
    ],
  },
  {
    email: "rrrrrr@hotmail.com",
    firstName: "rrr",
    lastName: "rrr",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "kasb",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شالية",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "rrrrrr@hotmail.com",
        region: "اللاذقية-كسب",
      },
    ],
  },
  {
    email: "rrr@hotmail.com",
    firstName: "rr",
    lastName: "rr",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "sahnaya",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "rrr@hotmail.com",
        region: "ريف دمشق-صحنايا",
      },
    ],
  },
  {
    email: "etabf59@gmail.com",
    firstName: "Etab",
    lastName: "F",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أقل من 100 ألف",
        email: "Etabf59@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "malcharif@darsoft.net",
    firstName: "Mohammed",
    lastName: "Charif",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "rukn-aldiyn",
    birthday: "1992-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 200 و الـ 239",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "malcharif@darsoft.net",
        region: "ريف دمشق-الزبداني",
      },
      {
        offer_type: "مكتب",
        business_offer: "إجار",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 300 ألف وأصغر من 400 ألف",
        email: "malcharif@darsoft.net",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "doaa1@gmail.com",
    firstName: "Doaa",
    lastName: "D",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almuhajirin",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 160 و الـ 179",
        price: "أكبر من 10 مليون وأصغر من 15 مليون",
        email: "doaa1@gmail.com",
        region: "دمشق-المهاجرين",
      },
    ],
  },
  {
    email: "alishipli1998@hotmail.com",
    firstName: "Ali",
    lastName: "Shipli",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 120 و الـ 139",
        price: "أكبر من 700 مليون وأصغر من 800 مليون",
        email: "alishipli1998@hotmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "r.zyadeh@gmail.com",
    firstName: "Rr",
    lastName: "Z",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "r.zyadeh@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "ayooshka114@gmail.com",
    firstName: "Ayoosh",
    lastName: "Ka",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "rukn-aldiyn",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أقل من 100 ألف",
        email: "ayooshka114@gmail.com",
        region: "دمشق-ركن الدين",
      },
    ],
  },
  {
    email: "shwshw.gh97@gmail.com",
    firstName: "shwshw",
    lastName: "gh",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "kafrisusa",
    birthday: "1997-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 3,000 و الـ 3,999",
        price: "أكبر من مليار وأصغر من 10 مليار",
        email: "shwshw.gh97@gmail.com",
        region: "دمشق-كفرسوسة",
      },
    ],
  },
  {
    email: "waad.ghussn10@gmail.com",
    firstName: "Waad",
    lastName: "Ghussn",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "alnabk",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "waad.ghussn10@gmail.com",
        region: "ريف دمشق-النبك",
      },
    ],
  },
  {
    email: "ayoosh2016@gmail.com",
    firstName: "Ayoosh",
    lastName: "A",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "kafrisusa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "ayoosh2016@gmail.com",
        region: "دمشق-كفرسوسة",
      },
    ],
  },
  {
    email: "mosup1995@gmail.com",
    firstName: "Mosup",
    lastName: "M",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "alzubdani",
    birthday: "1995-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 120 و الـ 139",
        price: "أقل من 100 ألف",
        email: "mosup1995@gmail.com",
        region: "ريف دمشق-الزبداني",
      },
    ],
  },
  {
    email: "almar39615@gmail.com",
    firstName: "Almar",
    lastName: "M",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaydan",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "almar39615@gmail.com",
        region: "دمشق-الميدان",
      },
      {
        offer_type: "شالية",
        business_offer: "إجار",
        area: "بين الـ 20 و الـ 39",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "almar39615@gmail.com",
        region: "اللاذقية-جبلة",
      },
    ],
  },
  {
    email: "ramamaks@gmail.com",
    firstName: "Rama",
    lastName: "Maks",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "kafrisusa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 500 ألف وأصغر من 600 ألف",
        email: "ramamaks@gmail.com",
        region: "دمشق-كفرسوسة",
      },
    ],
  },
  {
    email: "mostafajomaa@example.com",
    firstName: "Mostafa",
    lastName: "Jomaa",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "kafrisusa",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "شراء",
        area: "بين الـ 20,000 و الـ 100,000",
        price: "أكبر من مليار وأصغر من 10 مليار",
        email: "mostafajomaa@example.com",
        region: "دمشق-ركن الدين",
      },
      {
        offer_type: "أرض",
        business_offer: "شراء",
        area: "بين الـ 8,000 و الـ 9,999",
        price: "أكبر من 600 مليون وأصغر من 700 مليون",
        email: "mostafajomaa@example.com",
        region: "ريف دمشق-دوما",
      },
      {
        offer_type: "مستودع",
        business_offer: "إجار",
        area: "بين الـ 180 و الـ 199",
        price: "أكبر من 800 ألف وأصغر من مليون",
        email: "mostafajomaa@example.com",
        region: "دمشق-المزة",
      },
      {
        offer_type: "شالية",
        business_offer: "شراء",
        area: "بين الـ 320 و الـ 359",
        price: "أكبر من 260 مليون وأصغر من 300 مليون",
        email: "mostafajomaa@example.com",
        region: "اللاذقية-جبلة",
      },
      {
        offer_type: "قبو",
        business_offer: "إجار",
        area: "بين الـ 1,000 و الـ 1,199",
        price: "أكبر من 600 ألف وأصغر من 800 ألف",
        email: "mostafajomaa@example.com",
        region: "دمشق-القنوات",
      },
    ],
  },
  {
    email: "harryheba@gmail.com",
    firstName: "Heba",
    lastName: "Harry",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "almaydan",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 15 مليون وأصغر من 20 مليون",
        email: "harryheba@gmail.com",
        region: "دمشق-الميدان",
      },
    ],
  },
  {
    email: "moazberkdar9@gmail.com",
    firstName: "Moaz",
    lastName: "Berkdar",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "barza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 400 مليون وأصغر من 450 مليون",
        email: "moazberkdar9@gmail.com",
        region: "دمشق-برزة",
      },
    ],
  },
  {
    email: "mhmoudibrahim33@gmail.com",
    firstName: "Mahmoud",
    lastName: "Ibrahim",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "kafar-batnana",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 200 و الـ 239",
        price: "أكبر من 15 مليون وأصغر من 20 مليون",
        email: "mhmoudibrahim33@gmail.com",
        region: "ريف دمشق-كفر بطنا",
      },
    ],
  },
  {
    email: "mhmoodasmaeel35@gmail.com",
    firstName: "Mhmood",
    lastName: "asmaell",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "alzubdani",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "فيلا",
        business_offer: "إجار",
        area: "بين الـ 1,200 و الـ 1,599",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "mhmoodasmaeel35@gmail.com",
        region: "ريف دمشق-الزبداني",
      },
    ],
  },
  {
    email: "kareem.draawe3@gmail.com",
    firstName: "Kareem",
    lastName: "Draawe",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "alqisae",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 140 و الـ 159",
        price: "أكبر من 600 مليون وأصغر من 700 مليون",
        email: "kareem.draawe3@gmail.com",
        region: "دمشق-القصاع",
      },
    ],
  },
  {
    email: "roidaawad@gmail.com",
    firstName: "Roida",
    lastName: "Awad",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "إجار",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 150 ألف وأصغر من 200 ألف",
        email: "roidaawad@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "safaakiwan@gmail.com",
    firstName: "Safa",
    lastName: "Kiwan",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1992-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "شراء",
        area: "بين الـ 80 و الـ 99",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "safaakiwan@gmail.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "sh099711@gmail.com",
    firstName: "Sh",
    lastName: "Sy",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaydan",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 40 و الـ 59",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "sh099711@gmail.com",
        region: "دمشق-الميدان",
      },
    ],
  },
  {
    email: "anessaalkhalil@gamil.com",
    firstName: "Anessa",
    lastName: "Alkhalil",
    password: "123456789",
    role: "user",
    gender: "female",
    region: "jirmana",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "مزرعة",
        business_offer: "إجار",
        area: "بين الـ 200 و الـ 239",
        price: "أكبر من 100 ألف وأصغر من 150 ألف",
        email: "anessaalkhalil@gamil.com",
        region: "ريف دمشق-جرمانا",
      },
    ],
  },
  {
    email: "technomacx@gamil.com",
    firstName: "Techno",
    lastName: "Macx",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1998-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "بيت",
        business_offer: "شراء",
        area: "بين الـ 60 و الـ 79",
        price: "أكبر من 100 مليون وأصغر من 140 مليون",
        email: "technomacx@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
  {
    email: "mhmoodalkma22@gamil.com",
    firstName: "Techno",
    lastName: "Macx",
    password: "123456789",
    role: "user",
    gender: "male",
    region: "almaza",
    birthday: "1996-01-01",
    photo: null,
    phone: [],
    isDeleted: false,
    isVerified: true,
    searches: [
      {
        offer_type: "شقة",
        business_offer: "إجار",
        area: "بين الـ 100 و الـ 119",
        price: "أكبر من 200 ألف وأصغر من 300 ألف",
        email: "mhmoodalkma22@gmail.com",
        region: "دمشق-المزة",
      },
    ],
  },
];

module.exports = search_data;
