const allProvinces = [
  {
    id: "1",
    provinceArabicName: "دمشق",
    provinceEnglishName: "Damascus",
    provinceKey: "damascus",
    phoneCode: "+96311",
    regions: [
      {
        id: "1",
        regionArabicName: "جوبر",
        regionEnglishName: "jubar",
        regionKey: "jubar",
      },
      {
        id: "50",
        regionArabicName: "المزة",
        regionEnglishName: "almaza",
        regionKey: "almaza",
      },
      {
        id: "51",
        regionArabicName: "الميدان",
        regionEnglishName: "almaydan",
        regionKey: "almaydan",
      },
      {
        id: "52",
        regionArabicName: "الصالحية",
        regionEnglishName: "alsaalihia",
        regionKey: "alsaalihia",
      },
      {
        id: "53",
        regionArabicName: "القصاع",
        regionEnglishName: "alqisae",
        regionKey: "alqisae",
      },
      {
        id: "54",
        regionArabicName: "المهاجرين",
        regionEnglishName: "almuhajirin",
        regionKey: "almuhajirin",
      },
      {
        id: "55",
        regionArabicName: "ركن الدين",
        regionEnglishName: "rukn aldiyn",
        regionKey: "rukn-aldiyn",
      },
      {
        id: "56",
        regionArabicName: "برزة",
        regionEnglishName: "barza",
        regionKey: "barza",
      },
      {
        id: "57",
        regionArabicName: "دمشق القديمة",
        regionEnglishName: "dimashq alqadima",
        regionKey: "dimashq-alqadima",
      },
      {
        id: "58",
        regionArabicName: "دمر",
        regionEnglishName: "dummr",
        regionKey: "dummr",
      },
      {
        id: "59",
        regionArabicName: "كفرسوسة",
        regionEnglishName: "kafrisusa",
        regionKey: "kafrisusa",
      },
      {
        id: "60",
        regionArabicName: "القدم",
        regionEnglishName: "alqadam",
        regionKey: "alqadam",
      },
      {
        id: "62",
        regionArabicName: "الشاغور",
        regionEnglishName: "alshaaghwr",
        regionKey: "alshaaghwr",
      },
      {
        id: "63",
        regionArabicName: "ساروجا",
        regionEnglishName: "saruja",
        regionKey: "saruja",
      },
      {
        id: "64",
        regionArabicName: "القنوات",
        regionEnglishName: "alqanawat",
        regionKey: "alqanawat",
      },
      {
        id: "65",
        regionArabicName: "اليرموك",
        regionEnglishName: "alyarmuk",
        regionKey: "alyarmuk",
      },
      {
        id: "66",
        regionArabicName: "القابون",
        regionEnglishName: "alqabun",
        regionKey: "alqabun",
      },
    ],
  },
  {
    id: "2",
    provinceArabicName: "ريف دمشق",
    provinceEnglishName: "rif dimashq",
    provinceKey: "rif-dimashq",
    phoneCode: "+963",
    regions: [
      {
        id: "2",
        regionArabicName: "دوما",
        regionEnglishName: "dwma",
        regionKey: "dwma",
      },
      {
        id: "3",
        regionArabicName: "داريا",
        regionEnglishName: "darya",
        regionKey: "darya",
      },
      {
        id: "4",
        regionArabicName: "التل",
        regionEnglishName: "altall",
        regionKey: "altall",
      },
      {
        id: "5",
        regionArabicName: "النبك",
        regionEnglishName: "alnabk",
        regionKey: "alnabk",
      },
      {
        id: "6",
        regionArabicName: "يبرود",
        regionEnglishName: "yabrud",
        regionKey: "yabrud",
      },
      {
        id: "7",
        regionArabicName: "الزبداني",
        regionEnglishName: "alzubdani",
        regionKey: "alzubdani",
      },
      {
        id: "8",
        regionArabicName: "قطنا",
        regionEnglishName: "qatnana",
        regionKey: "qatnana",
      },
      {
        id: "9",
        regionArabicName: "عدرا",
        regionEnglishName: "Adra",
        regionKey: "adra",
      },
      {
        id: "159",
        regionArabicName: "مركز ريف دمشق",
        regionEnglishName: "markaz rif dimashq",
        regionKey: "markaz-rif-dimashq",
      },
      {
        id: "160",
        regionArabicName: "القطيفة",
        regionEnglishName: "alqatifa",
        regionKey: "alqatifa",
      },
      {
        id: "161",
        regionArabicName: "صيدنايا",
        regionEnglishName: "saydanaya",
        regionKey: "saydanaya",
      },
      {
        id: "162",
        regionArabicName: "رنكوس",
        regionEnglishName: "rinkus",
        regionKey: "rinkus",
      },
      {
        id: "163",
        regionArabicName: "الديماس",
        regionEnglishName: "aldiymas",
        regionKey: "aldiymas",
      },
      {
        id: "164",
        regionArabicName: "عين الفيجة",
        regionEnglishName: "eayn alfayja",
        regionKey: "eayn-alfayja",
      },
      {
        id: "165",
        regionArabicName: "مضايا",
        regionEnglishName: "madaya",
        regionKey: "madaya",
      },
      {
        id: "166",
        regionArabicName: "سرغايا",
        regionEnglishName: "sirghaya",
        regionKey: "sirghaya",
      },
      {
        id: "167",
        regionArabicName: "جيرود",
        regionEnglishName: "jerrod",
        regionKey: "jerrod",
      },
      {
        id: "168",
        regionArabicName: "معلولا",
        regionEnglishName: "maloula",
        regionKey: "maloula",
      },
      {
        id: "169",
        regionArabicName: "الرحيبة",
        regionEnglishName: "rahibh",
        regionKey: "rahibh",
      },
      {
        id: "170",
        regionArabicName: "دير عطية",
        regionEnglishName: "dir eatia",
        regionKey: "dir-eatia",
      },
      {
        id: "171",
        regionArabicName: "صحنايا",
        regionEnglishName: "sahnaya",
        regionKey: "sahnaya",
      },
      {
        id: "171",
        regionArabicName: "أشرفية صحنايا",
        regionEnglishName: "Ashrafiat sihnaya",
        regionKey: "ashrafiat-sihnaya",
      },
      {
        id: "172",
        regionArabicName: "الحجر الاسود",
        regionArabicName: "alhajar alaswd",
        regionKey: "alhajar-alaswd",
      },
      {
        id: "173",
        regionArabicName: "حرستا",
        regionEnglishName: "harasta",
        regionKey: "harasta",
      },
      {
        id: "174",
        regionArabicName: "السبع بيار",
        regionEnglishName: "alsabe biar",
        regionKey: "alsabe-biar",
      },
      {
        id: "175",
        regionArabicName: "النشابية",
        regionEnglishName: "alnashabia",
        regionKey: "alnashabia",
      },
      {
        id: "176",
        regionArabicName: "الغزلانية",
        regionEnglishName: "alghuzlania",
        regionKey: "alghuzlania",
      },
      {
        id: "177",
        regionArabicName: "حران العواميد",
        regionEnglishName: "haran aleawamid",
        regionKey: "haran-aleawamid",
      },
      {
        id: "178",
        regionArabicName: "سعسع",
        regionEnglishName: "sasa",
        regionKey: "sasa",
      },
      {
        id: "179",
        regionArabicName: "كناكر",
        regionEnglishName: "kanakir",
        regionKey: "kanakir",
      },
      {
        id: "180",
        regionArabicName: "بيت جن",
        regionEnglishName: "bayt jin",
        regionKey: "bayt-jin",
      },
      {
        id: "181",
        regionArabicName: "الكسوة",
        regionEnglishName: "alkaswa",
        regionKey: "alkaswa",
      },
      {
        id: "182",
        regionArabicName: "ببيلا",
        regionEnglishName: "babila",
        regionKey: "babila",
      },
      {
        id: "183",
        regionArabicName: "جرمانا",
        regionEnglishName: "jirmana",
        regionKey: "jirmana",
      },
      {
        id: "184",
        regionArabicName: "المليحة",
        regionEnglishName: "almaliha",
        regionKey: "almaliha",
      },
      {
        id: "185",
        regionArabicName: "عربين",
        regionEnglishName: "eirbin",
        regionKey: "eirbin",
      },
      {
        id: "186",
        regionArabicName: "قدسيا",
        regionEnglishName: "qudsiaa",
        regionKey: "qudsiaa",
      },
      {
        id: "186",
        regionArabicName: "ضاحية قدسيا",
        regionEnglishName: "dahiat qudsiaa",
        regionKey: "dahiat-qudsiaa",
      },
      {
        id: "187",
        regionArabicName: "عسال الورد",
        regionEnglishName: "eisal alward",
        regionKey: "eisal alward",
      },
      {
        id: "188",
        regionArabicName: "الضمير",
        regionEnglishName: "الضمير",
        regionKey: "aldamir",
      },
      {
        id: "189",
        regionArabicName: "كفر بطنا",
        regionEnglishName: "kafar batnana",
        regionKey: "kafar-batnana",
      },
      {
        id: "189",
        regionArabicName: "جديدة عرطوز",
        regionEnglishName: "Jadidat eartuz",
        regionKey: "jadidat-eartuz",
      },
      {
        id: "189",
        regionArabicName: "جمرايا",
        regionEnglishName: "Jamraya",
        regionKey: "jamraya",
      },
      {
        id: "189",
        regionArabicName: "الهامة",
        regionEnglishName: "alhama",
        regionKey: "alhama",
      },
      {
        id: "189",
        regionArabicName: "جديدة الفضل",
        regionEnglishName: "jadidat alfadl",
        regionKey: "jadidat-alfadl",
      },
      {
        id: "189",
        regionArabicName: "عقربا",
        regionEnglishName: "eaqraba",
        regionKey: "eaqraba",
      },
      {
        id: "189",
        regionArabicName: "جديده الشيباني",
        regionEnglishName: "jadiduh alshaybaniu",
        regionKey: "jadiduh-alshaybaniu",
      },
      {
        id: "189",
        regionArabicName: "اشرفيه الوادي",
        regionEnglishName: "ashrfih alwadi",
        regionKey: "ashrfih-alwadi",
      },
      {
        id: "189",
        regionArabicName: "حزه",
        regionEnglishName: "hazah",
        regionKey: "hazah",
      },
    ],
  },
  {
    id: "3",
    provinceArabicName: "حلب",
    provinceEnglishName: "Aleppo",
    provinceKey: "aleppo",
    phoneCode: "+96321",
    regions: [
      {
        id: "10",
        regionArabicName: "الباب",
        regionEnglishName: "albab",
        regionKey: "albab",
      },
      {
        id: "11",
        regionArabicName: "منبج",
        regionEnglishName: "minbaj",
        regionKey: "minbaj",
      },
      {
        id: "12",
        regionArabicName: "اعزار",
        regionEnglishName: "اعزار",
        regionKey: "اعزار",
      },
      {
        id: "13",
        regionArabicName: "السفيرة",
        regionEnglishName: "alsafira",
        regionKey: "alsafira",
      },
      {
        id: "14",
        regionArabicName: "عفرين",
        regionEnglishName: "eifrin",
        regionKey: "eifrin",
      },
      {
        id: "15",
        regionArabicName: "عين العرب",
        regionEnglishName: "eayn alearab",
        regionKey: "eayn-alearab",
      },
      {
        id: "16",
        regionArabicName: "جربلس",
        regionEnglishName: "jarabulus",
        regionKey: "jarabulus",
      },
      {
        id: "98",
        regionArabicName: "رسم حرمل الامام",
        regionEnglishName: "rasam harmal alamam",
        regionKey: "rasam-harmal-alamam",
      },
      {
        id: "90",
        regionArabicName: "مركز حلب",
        regionEnglishName: "markaz halab",
        regionKey: "markaz-halab",
      },
      {
        id: "91",
        regionArabicName: "جبل سمعان",
        regionEnglishName: "jabal simean",
        regionKey: "jabal-simean",
      },
      {
        id: "94",
        regionArabicName: "تل رفعت",
        regionEnglishName: "tal rufiet",
        regionKey: "tal-rufiet",
      },
      {
        id: "104",
        regionArabicName: "تل الضمان",
        regionEnglishName: "tal aldaman",
        regionKey: "tal-aldaman",
      },
      {
        id: "105",
        regionArabicName: "دارة عزة",
        regionEnglishName: "darat eiza",
        regionKey: "darat-eiza",
      },
      {
        id: "119",
        regionArabicName: "ابو قلقل",
        regionEnglishName: "abw qalqal",
        regionKey: "abw-qalqal",
      },
      {
        id: "99",
        regionArabicName: "دير حافر",
        regionEnglishName: "dir hafir",
        regionKey: "dir-hafir",
      },
      {
        id: "92",
        regionArabicName: "نبل",
        regionEnglishName: "nubl",
        regionKey: "nubl",
      },
      {
        id: "93",
        regionArabicName: "مارع",
        regionEnglishName: "maria",
        regionKey: "maria",
      },
      {
        id: "95",
        regionArabicName: "الراعي",
        regionEnglishName: "alraaei",
        regionKey: "alraaei",
      },
      {
        id: "96",
        regionArabicName: "عريمة",
        regionEnglishName: "earima",
        regionKey: "earima",
      },
      {
        id: "97",
        regionArabicName: "تادف",
        regionEnglishName: "tedef",
        regionKey: "tedef",
      },
      {
        id: "100",
        regionArabicName: "كويرس",
        regionEnglishName: "kwyrs",
        regionKey: "kwyrs",
      },
      {
        id: "101",
        regionArabicName: "بنان",
        regionArabicName: "bnan",
        regionKey: "bnan",
      },
      {
        id: "102",
        regionArabicName: "خناصر",
        regionEnglishName: "khannasr",
        regionKey: "khannasr",
      },
      {
        id: "103",
        regionArabicName: "الحاجب",
        regionEnglishName: "alhajib",
        regionKey: "alhajib",
      },
      {
        id: "106",
        regionArabicName: "الاتارب",
        regionEnglishName: "alatarb",
        regionKey: "alatarb",
      },
      {
        id: "107",
        regionArabicName: "حريتان",
        regionEnglishName: "harytan",
        regionKey: "harytan",
      },
      {
        id: "108",
        regionArabicName: "غندورة",
        regionEnglishName: "ghandura",
        regionKey: "ghandura",
      },
      {
        id: "109",
        regionArabicName: "الخفسة",
        regionEnglishName: "alkhafsa",
        regionKey: "alkhafsa",
      },
      {
        id: "110",
        regionArabicName: "اخترين",
        regionEnglishName: "akhtirin",
        regionKey: "akhtirin",
      },
      {
        id: "111",
        regionArabicName: "راجو",
        regionEnglishName: "rajw",
        regionKey: "rajw",
      },
      {
        id: "112",
        regionArabicName: "مسكنة",
        regionEnglishName: "muskana",
        regionKey: "muskana",
      },
      {
        id: "114",
        regionArabicName: "الزربة",
        regionEnglishName: "alzurba",
        regionKey: "alzurba",
      },
      {
        id: "115",
        regionArabicName: "بليل",
        regionEnglishName: "bilil",
        regionKey: "bilil",
      },
      {
        id: "116",
        regionArabicName: "معبطلي",
        regionEnglishName: "mueabtali",
        regionKey: "mueabtali",
      },
      {
        id: "117",
        regionArabicName: "شران",
        regionEnglishName: "shuran",
        regionKey: "shuran",
      },
      {
        id: "118",
        regionArabicName: "صرين",
        regionEnglishName: "suryn",
        regionKey: "suryn",
      },
      {
        id: "118",
        regionArabicName: "الحمدانيه",
        regionEnglishName: "Alhamdania",
        regionKey: "alhamdania",
      },
      {
        id: "118",
        regionArabicName: "سيف الدوله",
        regionEnglishName: "sayf alduwalih",
        regionKey: "sayf-alduwalih",
      },
    ],
  },
  {
    id: "4",
    provinceArabicName: "حمص",
    provinceEnglishName: "Homs",
    provinceKey: "homs",
    phoneCode: "+96331",
    regions: [
      {
        id: "130",
        regionArabicName: "مركز حمص",
        regionEnglishName: "markaz hims",
        regionKey: "markaz-hims",
      },
      {
        id: "134",
        regionArabicName: "جب الجراح",
        regionEnglishName: "jibu aljaraah",
        regionKey: "jibu-aljaraah",
      },
      {
        id: "141",
        regionArabicName: "عين النسر",
        regionEnglishName: "eayn alnasr",
        regionKey: "eayn-alnasr",
      },
      {
        id: "143",
        regionArabicName: "خربة التين",
        regionEnglishName: "kharbat altiyn",
        regionKey: "kharbat-altiyn",
      },
      {
        id: "17",
        regionArabicName: "الرستن",
        regionEnglishName: "alrustun",
        regionKey: "alrustun",
      },
      {
        id: "18",
        regionArabicName: "تدمر",
        regionEnglishName: "tadamar",
        regionKey: "tadamar",
      },
      {
        id: "19",
        regionArabicName: "المخرم",
        regionEnglishName: "almukhram",
        regionKey: "almukhram",
      },
      {
        id: "20",
        regionArabicName: "تلكلخ",
        regionEnglishName: "tilkalikh",
        regionKey: "tilkalikh",
      },
      {
        id: "21",
        regionArabicName: "القصير",
        regionEnglishName: "alqasayr",
        regionKey: "alqasayr",
      },
      {
        id: "131",
        regionArabicName: "القبو",
        regionEnglishName: "alqabw",
        regionKey: "alqabw",
      },
      {
        id: "132",
        regionArabicName: "مهين",
        regionEnglishName: "mahin",
        regionKey: "mahin",
      },
      {
        id: "133",
        regionArabicName: "القريتين",
        regionEnglishName: "alqaryatayn",
        regionKey: "alqaryatayn",
      },
      {
        id: "135",
        regionArabicName: "السخنة",
        regionEnglishName: "alsukhna",
        regionKey: "alsukhna",
      },
      {
        id: "136",
        regionArabicName: "صدد",
        regionEnglishName: "sadad",
        regionKey: "sadad",
      },
      {
        id: "137",
        regionArabicName: "شين",
        regionEnglishName: "shyn",
        regionKey: "shyn",
      },
      {
        id: "138",
        regionArabicName: "حسياء",
        regionEnglishName: "hisya'",
        regionKey: "hisya'",
      },
      {
        id: "139",
        regionArabicName: "الفرقلس",
        regionEnglishName: "alfirqals",
        regionKey: "alfirqals",
      },
      {
        id: "140",
        regionArabicName: "الحواش",
        regionEnglishName: "alhawash",
        regionKey: "alhawash",
      },
      {
        id: "142",
        regionArabicName: "الناصرة",
        regionEnglishName: "alnaasira",
        regionKey: "alnaasira",
      },
      {
        id: "144",
        regionArabicName: "حديدة",
        regionArabicName: "hadida",
        regionKey: "hadida",
      },
      {
        id: "145",
        regionArabicName: "الرقاما",
        regionEnglishName: "alriqama",
        regionKey: "alriqama",
      },
      {
        id: "145",
        regionArabicName: "العزيزيه",
        regionEnglishName: "aleazizih",
        regionKey: "aleazizih",
      },
      {
        id: "145",
        regionArabicName: "الجميليه",
        regionEnglishName: "aljamilih",
        regionKey: "aljamilih",
      },
    ],
  },
  {
    id: "5",
    provinceArabicName: "اللاذقية",
    provinceEnglishName: "Latakia",
    provinceKey: "latakia",
    phoneCode: "+96341",
    regions: [
      {
        id: "76",
        regionArabicName: "مركز اللاذقية",
        regionEnglishName: "markaz allaadhiqia",
        regionKey: "markaz-allaadhiqia",
      },
      {
        id: "78",
        regionArabicName: "قسطل معاف",
        regionEnglishName: "qastal maeaf",
        regionKey: "qastal-maeaf",
      },
      {
        id: "84",
        regionArabicName: "عين البيضا",
        regionEnglishName: "eayn albayda",
        regionKey: "eayn-albayda",
      },
      {
        id: "86",
        regionArabicName: "جوبة برغال",
        regionEnglishName: "jubat birghal",
        regionKey: "jubat-birghal",
      },
      {
        id: "87",
        regionArabicName: "عين الشرقية",
        regionEnglishName: "eayn alsharqia",
        regionKey: "eayn-alsharqia",
      },
      {
        id: "88",
        regionArabicName: "بيت ياشوط",
        regionEnglishName: "bayt yashut",
        regionKey: "bayt-yashut",
      },

      {
        id: "22",
        regionArabicName: "جبلة",
        regionEnglishName: "jabla",
        regionKey: "jabla",
      },
      {
        id: "23",
        regionArabicName: "الحفة",
        regionEnglishName: "alhafa",
        regionKey: "alhafa",
      },
      {
        id: "24",
        regionArabicName: "القرداحة",
        regionEnglishName: "alqirdaha",
        regionKey: "alqirdaha",
      },
      {
        id: "77",
        regionArabicName: "كسب",
        regionEnglishName: "kasb",
        regionKey: "kasb",
      },
      {
        id: "79",
        regionArabicName: "البهلولية",
        regionEnglishName: "albahlulia",
        regionKey: "albahlulia",
      },
      {
        id: "80",
        regionArabicName: "ربيعة",
        regionEnglishName: "rabiea",
        regionKey: "rabiea",
      },
      {
        id: "81",
        regionArabicName: "المزيرعة",
        regionEnglishName: "almuzayraea",
        regionKey: "almuzayraea",
      },
      {
        id: "82",
        regionArabicName: "الفاخورة",
        regionArabicName: "alfakhura",
        regionKey: "alfakhura",
      },
      {
        id: "83",
        regionArabicName: "هنادي",
        regionEnglishName: "hunadi",
        regionKey: "hunadi",
      },
      {
        id: "85",
        regionArabicName: "صلنفة",
        regionEnglishName: "salnafa",
        regionKey: "salnafa",
      },
      {
        id: "89",
        regionArabicName: "الدالية",
        regionEnglishName: "aldaalia",
        regionKey: "aldaalia",
      },
      {
        id: "89",
        regionArabicName: "الجديدة",
        regionEnglishName: "aljadida",
        regionKey: "aljadida",
      },
    ],
  },
  {
    id: "6",
    provinceArabicName: "حماه",
    provinceEnglishName: "Hama",
    provinceKey: "hama",
    phoneCode: "+96333",
    regions: [
      {
        id: "121",
        regionArabicName: "مركز حماة",
        regionEnglishName: "markaz hamaa",
        regionKey: "markaz-hamaa",
      },
      {
        id: "123",
        regionArabicName: "بري شرقي",
        regionEnglishName: "bariy sharqiun",
        regionKey: "bariy-sharqiun",
      },
      {
        id: "124",
        regionArabicName: "وادي العيون",
        regionEnglishName: "wadi aleuyun",
        regionKey: "wadi-aleuyun",
      },
      {
        id: "125",
        regionArabicName: "جب رملة",
        regionEnglishName: "jabu ramla",
        regionKey: "jabu-ramla",
      },
      {
        id: "127",
        regionArabicName: "عين حلاقيم",
        regionEnglishName: "eayn halaqim",
        regionKey: "eayn-halaqim",
      },
      {
        id: "25",
        regionArabicName: "سلحب",
        regionEnglishName: "سلحب",
        regionKey: "",
      },
      {
        id: "26",
        regionArabicName: "السقيلبية",
        regionEnglishName: "alsuqaylabi",
        regionKey: "alsuqaylabi",
      },
      {
        id: "27",
        regionArabicName: "محردة",
        regionEnglishName: "muharada",
        regionKey: "muharada",
      },
      {
        id: "28",
        regionArabicName: "مصياف",
        regionEnglishName: "misyaf",
        regionKey: "misyaf",
      },
      {
        id: "29",
        regionArabicName: "السلمية",
        regionEnglishName: "alsilmia",
        regionKey: "alsilmia",
      },
      {
        id: "122",
        regionArabicName: "الصبورة",
        regionEnglishName: "alsubura",
        regionKey: "alsubura",
      },
      {
        id: "126",
        regionArabicName: "عوج",
        regionEnglishName: "ewj",
        regionKey: "ewj",
      },
      {
        id: "128",
        regionArabicName: "جورين",
        regionEnglishName: "jurin",
        regionKey: "jurin",
      },
      {
        id: "129",
        regionArabicName: "شطحة",
        regionEnglishName: "shatha",
        regionKey: "shatha",
      },
    ],
  },
  {
    id: "7",
    provinceArabicName: "طرطوس",
    provinceEnglishName: "Tartous",
    provinceKey: "tartous",
    phoneCode: "+96343",
    regions: [
      {
        id: "67",
        regionArabicName: "مركز طرطوس",
        regionEnglishName: "markaz tartus",
        regionKey: "markaz-tartus",
      },
      {
        id: "70",
        regionArabicName: "خربة المعزة",
        regionEnglishName: "kharbat almaeaza",
        regionKey: "kharbat-almaeaza",
      },
      {
        id: "73",
        regionArabicName: "مشتى الحلو",
        regionEnglishName: "mashtaa alhulw",
        regionKey: "mashtaa-alhulw",
      },
      {
        id: "75",
        regionArabicName: "دوير رسلان",
        regionEnglishName: "dwyr raslan",
        regionKey: "dwyr-raslan",
      },
      {
        id: "30",
        regionArabicName: "الشيخ بدر",
        regionEnglishName: "alshaykh badr",
        regionKey: "alshaykh-badr",
      },

      {
        id: "31",
        regionArabicName: "بانياس",
        regionEnglishName: "banyas",
        regionKey: "banyas",
      },
      {
        id: "32",
        regionArabicName: "صافيتا",
        regionEnglishName: "safita",
        regionKey: "safita",
      },
      {
        id: "33",
        regionArabicName: "الدريكيش",
        regionEnglishName: "aldarikish",
        regionKey: "aldarikish",
      },
      {
        id: "68",
        regionArabicName: "الصفصافة",
        regionArabicName: "alsafsafa",
        regionKey: "alsafsafa",
      },
      {
        id: "69",
        regionArabicName: "الحميدية",
        regionEnglishName: "alhumidia",
        regionKey: "alhumidia",
      },
      {
        id: "71",
        regionArabicName: "الخوابي",
        regionEnglishName: "alkhawabi",
        regionKey: "alkhawabi",
      },
      {
        id: "72",
        regionArabicName: "كريمة",
        regionEnglishName: "karima",
        regionKey: "karima",
      },
      {
        id: "74",
        regionArabicName: "القدموس",
        regionEnglishName: "alqidmus",
        regionKey: "alqidmus",
      },
      {
        id: "74",
        regionArabicName: "بملكه",
        regionEnglishName: "bimilkih",
        regionKey: "bimilkih",
      },
    ],
  },
  {
    id: "8",
    provinceArabicName: "الرقة",
    provinceEnglishName: "al raqa",
    provinceKey: "al-raqa",
    phoneCode: "+96322",
    regions: [
      {
        id: "234",
        regionArabicName: "مركز الرقة",
        regionEnglishName: "markaz alraqa",
        regionKey: "markaz-alraqa",
      },
      {
        id: "238",
        regionArabicName: "عين عيسى",
        regionEnglishName: "eayn eisaa",
        regionKey: "eayn-eisaa",
      },
      {
        id: "34",
        regionArabicName: "تل أبيض",
        regionEnglishName: "tal abyad",
        regionKey: "tal-abyad",
      },

      {
        id: "35",
        regionArabicName: "الثورة",
        regionEnglishName: "althawra",
        regionKey: "althawra",
      },
      {
        id: "235",
        regionArabicName: "معدان",
        regionEnglishName: "muedaan",
        regionKey: "muedaan",
      },
      {
        id: "236",
        regionArabicName: "الكرامة",
        regionEnglishName: "alkarama",
        regionKey: "alkarama",
      },
      {
        id: "237",
        regionArabicName: "السبخة",
        regionEnglishName: "alsabkha",
        regionKey: "alsabkha",
      },
      {
        id: "239",
        regionArabicName: "الجرنية",
        regionEnglishName: "aljarnia",
        regionKey: "aljarnia",
      },
      {
        id: "240",
        regionArabicName: "المنصورة",
        regionEnglishName: "almansura",
        regionKey: "almansura",
      },
      {
        id: "241",
        regionArabicName: "سلوك",
        regionEnglishName: "suluk",
        regionKey: "suluk",
      },
    ],
  },
  {
    id: "9",
    provinceArabicName: "دير الزور",
    provinceEnglishName: "der alzoor",
    provinceKey: "der-alzoor",
    phoneCode: "+96351",
    regions: [
      {
        id: "209",
        regionArabicName: "مركز ديرالزور",
        regionEnglishName: "markaz dyralzur",
        regionKey: "markaz-dyralzur",
      },
      {
        id: "36",
        regionArabicName: "البوكمال",
        regionEnglishName: "albukmal",
        regionKey: "albukmal",
      },
      {
        id: "37",
        regionArabicName: "الميادين",
        regionEnglishName: "almayadin",
        regionKey: "almayadin",
      },
      {
        id: "210",
        regionArabicName: "هجين",
        regionEnglishName: "hajin",
        regionKey: "hajin",
      },
      {
        id: "211",
        regionArabicName: "الجلاء",
        regionEnglishName: "aljala",
        regionKey: "aljala",
      },
      {
        id: "212",
        regionArabicName: "سوسة",
        regionEnglishName: "swsa",
        regionKey: "swsa",
      },
      {
        id: "213",
        regionArabicName: "ذبيان",
        regionEnglishName: "dhubyan",
        regionKey: "dhubyan",
      },
      {
        id: "214",
        regionArabicName: "عشارة",
        regionEnglishName: "eashara",
        regionKey: "eashara",
      },
      {
        id: "215",
        regionArabicName: "بصيرة",
        regionEnglishName: "busira",
        regionKey: "busira",
      },
      {
        id: "216",
        regionArabicName: "التبني",
        regionEnglishName: "altabaniy",
        regionKey: "altabaniy",
      },
      {
        id: "217",
        regionArabicName: "خشام",
        regionEnglishName: "khisham",
        regionKey: "khisham",
      },
      {
        id: "218",
        regionArabicName: "صور",
        regionEnglishName: "suar",
        regionKey: "suar",
      },
      {
        id: "219",
        regionArabicName: "كسرة",
        regionEnglishName: "kasra",
        regionKey: "kasra",
      },
      {
        id: "220",
        regionArabicName: "موحسن",
        regionEnglishName: "muhasan",
        regionKey: "muhasan",
      },
    ],
  },
  {
    id: "10",
    provinceArabicName: "السويداء",
    provinceEnglishName: "al suwayda",
    provinceKey: "al-suwayda",
    phoneCode: "+96316",
    regions: [
      {
        id: "146",
        regionArabicName: "مركز السويداء",
        regionEnglishName: "markaz alsuwayda",
        regionKey: "markaz-alsuwayda",
      },
      {
        id: "153",
        regionArabicName: "الصورة الصغيرة",
        regionEnglishName: "alsuwrat alsaghira",
        regionKey: "alsuwrat-alsaghira",
      },

      {
        id: "38",
        regionArabicName: "شهبا",
        regionEnglishName: "shuhbana",
        regionKey: "shuhbana",
      },
      {
        id: "147",
        regionArabicName: "صلخد",
        regionEnglishName: "salkhad",
        regionKey: "salkhad",
      },
      {
        id: "148",
        regionArabicName: "المشلف",
        regionEnglishName: "almushalaf",
        regionKey: "almushalaf",
      },
      {
        id: "149",
        regionArabicName: "المزرعة",
        regionEnglishName: "almazraea",
        regionKey: "almazraea",
      },
      {
        id: "150",
        regionArabicName: "ملح",
        regionEnglishName: "milh",
        regionKey: "milh",
      },
      {
        id: "151",
        regionArabicName: "الغارية",
        regionEnglishName: "algharia",
        regionKey: "algharia",
      },
      {
        id: "152",
        regionArabicName: "الفريا",
        regionEnglishName: "alfirya",
        regionKey: "alfirya",
      },
      {
        id: "154",
        regionArabicName: "شقا",
        regionEnglishName: "shaqana",
        regionKey: "shaqana",
      },
      {
        id: "155",
        regionArabicName: "ذيبين",
        regionEnglishName: "dhibin",
        regionKey: "dhibin",
      },
      {
        id: "156",
        regionArabicName: "المشنف",
        regionEnglishName: "almushanaf",
        regionKey: "almushanaf",
      },
      {
        id: "157",
        regionArabicName: "العريقة",
        regionEnglishName: "aleariqa",
        regionKey: "aleariqa",
      },
      {
        id: "158",
        regionArabicName: "القريا",
        regionEnglishName: "alqirya",
        regionKey: "alqirya",
      },
    ],
  },
  {
    id: "11",
    provinceArabicName: "الحسكة",
    provinceEnglishName: "al hasaka",
    provinceKey: "al-hasaka",
    phoneCode: "+96352",
    regions: [
      {
        id: "221",
        regionArabicName: "مركز الحسكة",
        regionEnglishName: "مركز الحسكة",
        regionKey: "markaz-alhasaka",
      },
      {
        id: "40",
        regionArabicName: "رأس العين",
        regionEnglishName: "ras aleayn",
        regionKey: "ras-aleayn",
      },
      {
        id: "222",
        regionArabicName: "تل حميس",
        regionEnglishName: "tal hamis",
        regionKey: "tal-hamis",
      },
      {
        id: "226",
        regionArabicName: "تل تمر",
        regionEnglishName: "tal tamur",
        regionKey: "tal-tamur",
      },
      {
        id: "233",
        regionArabicName: "بئر الحلو الوردية",
        regionEnglishName: "bir alhulw alwardia",
        regionKey: "bir-سalhulw-alwardia",
      },

      {
        id: "39",
        regionArabicName: "القامشلي",
        regionEnglishName: "alqamishli",
        regionKey: "alqamishli",
      },
      {
        id: "41",
        regionArabicName: "المالكية",
        regionEnglishName: "almalikia",
        regionKey: "almalikia",
      },
      {
        id: "223",
        regionArabicName: "عامودا",
        regionEnglishName: "eamuda",
        regionKey: "eamuda",
      },
      {
        id: "224",
        regionArabicName: "جوادية",
        regionEnglishName: "jawadia",
        regionKey: "jawadia",
      },
      {
        id: "225",
        regionArabicName: "يعربية",
        regionEnglishName: "yaeribia",
        regionKey: "yaeribia",
      },
      {
        id: "227",
        regionArabicName: "الشدادة",
        regionEnglishName: "alshadada",
        regionKey: "alshadada",
      },
      {
        id: "228",
        regionArabicName: "مركدة",
        regionEnglishName: "markada",
        regionKey: "markada",
      },
      {
        id: "229",
        regionArabicName: "العريشة",
        regionEnglishName: "alearisha",
        regionKey: "alearisha",
      },
      {
        id: "230",
        regionArabicName: "الهول",
        regionEnglishName: "alhawl",
        regionKey: "alhawl",
      },
      {
        id: "231",
        regionArabicName: "درباسية",
        regionEnglishName: "dirbasia",
        regionKey: "dirbasia",
      },
      {
        id: "232",
        regionArabicName: "قحطانية",
        regionEnglishName: "qahtany",
        regionKey: "qahtany",
      },
    ],
  },
  {
    id: "12",
    provinceArabicName: "درعا",
    provinceEnglishName: "Daraa",
    provinceKey: "daraa",
    phoneCode: "+96315",
    regions: [
      {
        id: "193",
        regionArabicName: "مركز درعا",
        regionEnglishName: "markaz direa",
        regionKey: "markaz-direa",
      },
      {
        id: "195",
        regionArabicName: "بصرى الشام",
        regionEnglishName: "busraa alshaam",
        regionKey: "busraa-alshaam",
      },
      {
        id: "196",
        regionArabicName: "خربة غزالة",
        regionEnglishName: "kharibat ghazala",
        regionKey: "kharibat-ghazala",
      },
      {
        id: "205",
        regionArabicName: "الشيخ مسكين",
        regionEnglishName: "alshaykh miskin",
        regionKey: "alshaykh-miskin",
      },
      {
        id: "42",
        regionArabicName: "ازرع",
        regionEnglishName: "izrae",
        regionKey: "izrae",
      },
      {
        id: "43",
        regionArabicName: "الصنمين",
        regionEnglishName: "alsanamayn",
        regionKey: "alsanamayn",
      },
      {
        id: "194",
        regionArabicName: "غباغب",
        regionEnglishName: "ghabaghib",
        regionKey: "ghabaghib",
      },
      {
        id: "197",
        regionArabicName: "داعل",
        regionEnglishName: "daeil",
        regionKey: "daeil",
      },
      {
        id: "197",
        regionArabicName: "طفس",
        regionEnglishName: "tafs",
        regionKey: "tafs",
      },
      {
        id: "198",
        regionArabicName: "مزيريب",
        regionEnglishName: "mazirib",
        regionKey: "mazirib",
      },
      {
        id: "199",
        regionArabicName: "الشجرة",
        regionEnglishName: "alshajara",
        regionKey: "alshajara",
      },
      {
        id: "200",
        regionArabicName: "الجيزة",
        regionEnglishName: "aljiza",
        regionKey: "aljiza",
      },
      {
        id: "201",
        regionArabicName: "المسيفرة",
        regionEnglishName: "almusayfira",
        regionKey: "almusayfira",
      },
      {
        id: "202",
        regionArabicName: "جاسم",
        regionEnglishName: "jasim",
        regionKey: "jasim",
      },
      {
        id: "203",
        regionArabicName: "الحراك",
        regionEnglishName: "alharak",
        regionKey: "alharak",
      },
      {
        id: "204",
        regionArabicName: "نوى",
        regionEnglishName: "nuaa",
        regionKey: "nuaa",
      },
      {
        id: "206",
        regionArabicName: "تسيل",
        regionEnglishName: "tasil",
        regionKey: "tasil",
      },
      {
        id: "207",
        regionArabicName: "المسمية",
        regionEnglishName: "almusamiya",
        regionKey: "almusamiya",
      },
    ],
  },
  {
    id: "13",
    provinceArabicName: "إدلب",
    provinceEnglishName: "Idlib",
    provinceKey: "idlib",
    phoneCode: "+96323",
    regions: [
      {
        id: "242",
        regionArabicName: "مركز إدلب",
        regionEnglishName: "markaz iidlib",
        regionKey: "markaz-iidlib",
      },
      {
        id: "46",
        regionArabicName: "جسر الشغور",
        regionEnglishName: "jisr alshughur",
        regionKey: "jisr-alshughur",
      },
      {
        id: "47",
        regionArabicName: "معر تمصرين",
        regionEnglishName: "maeartimisirin",
        regionKey: "maeartimisirin",
      },
      {
        id: "249",
        regionArabicName: "كفر نبل",
        regionEnglishName: "kafr nubl",
        regionKey: "kafr-nubl",
      },
      {
        id: "250",
        regionArabicName: "خان شيخون",
        regionEnglishName: "khan shykhun",
        regionKey: "khan-shykhun",
      },
      {
        id: "254",
        regionArabicName: "أبو الظهور",
        regionEnglishName: "abu alzuhur",
        regionKey: "abu-alzuhur",
      },
      {
        id: "257",
        regionArabicName: "كفر تخاريم",
        regionEnglishName: "kafar takharim",
        regionKey: "kafar-takharim",
      },
      {
        id: "44",
        regionArabicName: "معرة النعمان",
        regionEnglishName: "maearat alnueman",
        regionKey: "maearat-alnueman",
      },

      {
        id: "45",
        regionArabicName: "أريحا",
        regionEnglishName: "ariha",
        regionKey: "ariha",
      },
      {
        id: "48",
        regionArabicName: "حارم",
        regionEnglishName: "harim",
        regionKey: "harim",
      },
      {
        id: "243",
        regionArabicName: "دركوش",
        regionEnglishName: "darkosh",
        regionKey: "darkosh",
      },
      {
        id: "244",
        regionArabicName: "بداما",
        regionEnglishName: "badamana",
        regionKey: "badamana",
      },
      {
        id: "245",
        regionArabicName: "سلقين",
        regionEnglishName: "salqin",
        regionKey: "salqin",
      },
      {
        id: "246",
        regionArabicName: "سنجار",
        regionEnglishName: "sinjar",
        regionKey: "sinjar",
      },
      {
        id: "247",
        regionArabicName: "حيش",
        regionEnglishName: "hysh",
        regionKey: "hysh",
      },
      {
        id: "248",
        regionArabicName: "التمانعة",
        regionEnglishName: "altamanuea",
        regionKey: "altamanuea",
      },
      {
        id: "251",
        regionArabicName: "تفتناز",
        regionEnglishName: "taftanaz",
        regionKey: "taftanaz",
      },
      {
        id: "252",
        regionArabicName: "سراقب",
        regionEnglishName: "saraqib",
        regionKey: "saraqib",
      },
      {
        id: "253",
        regionArabicName: "بنش",
        regionEnglishName: "binsh",
        regionKey: "binsh",
      },
      {
        id: "255",
        regionArabicName: "أرمناز",
        regionEnglishName: "arminaz",
        regionKey: "arminaz",
      },
      {
        id: "256",
        regionArabicName: "قورقينا",
        regionEnglishName: "qawriqina",
        regionKey: "qawriqina",
      },
      {
        id: "258",
        regionArabicName: "دانا",
        regionEnglishName: "dana",
        regionKey: "dana",
      },
      {
        id: "259",
        regionArabicName: "الجانودية",
        regionEnglishName: "aljanudia",
        regionKey: "aljanudia",
      },
      {
        id: "260",
        regionArabicName: "بداما",
        regionEnglishName: "badamana",
        regionKey: "badamana",
      },
      {
        id: "261",
        regionArabicName: "محمبل",
        regionEnglishName: "mahmibl",
        regionKey: "mahmibl",
      },
      {
        id: "262",
        regionArabicName: "احسم",
        regionEnglishName: "aihsim",
        regionKey: "aihsim",
      },
    ],
  },
  {
    id: "14",
    provinceArabicName: "القنيطرة",
    provinceEnglishName: "al qunaytara",
    provinceKey: "al-qunaytara",
    phoneCode: "+96314",
    regions: [
      {
        id: "190",
        regionArabicName: "مركز القنيطرة",
        regionEnglishName: "markaz alqunaytara",
        regionKey: "markaz alqunaytara",
      },
      {
        id: "191",
        regionArabicName: "خان أرنبة",
        regionEnglishName: "khan arnaba",
        regionKey: "khan arnaba",
      },
      {
        id: "49",
        regionArabicName: "فيق",
        regionEnglishName: "fiq",
        regionKey: "fiq",
      },
      {
        id: "192",
        regionArabicName: "الخشنية",
        regionEnglishName: "alkhashnia",
        regionKey: "alkhashnia",
      },
    ],
  },
];

module.exports = allProvinces;
